# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0dfe690fc5673da1faaad0ec0149d32c7bb36b8b1073d326f678f35f738d8c1fa75af0cde6d30bceed72dbf575c66295245bbc37858c2551231316008e65f8e6

test:
  secret_key_base: 93e9c687489340aca330d4de89fef270d7ebafd3bb201659c850edf5cff41211ab4a93586e0c750192e5e050819c78d700c3de1f13e8c5bd82a1908ff231ecfc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
